# Generated by Django 5.0 on 2024-01-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnfermeria', '0002_nurse_alter_turno_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='francoprogramado',
            name='Apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='francoprogramado',
            name='Nombre',
            field=models.CharField(default='ValorPorDefecto', max_length=200),
        ),
        migrations.AddField(
            model_name='licencia',
            name='Apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='licencia',
            name='Nombre',
            field=models.CharField(default='your_default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='turno',
            name='Apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Nombre',
            field=models.CharField(max_length=200),
        ),
    ]
